[package]
name = "caps-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
winapi = { version = "0.3", features = ["winuser", "libloaderapi", "errhandlingapi", "processthreadsapi"] }
user32-sys = "0.2"
